import { readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { parseJiraXml, splitPassages } from './jira-xml';
import { sniffTicketFormat } from './sniff';

/**
 * A real export, redacted.
 *
 * Every structural quirk is the one Jira wrote: the leading HTML comment with
 * no XML declaration, the doubly-escaped HTML description, the numeric
 * character reference in a display name, and the table row with more cells than
 * its header has columns. Those are the cases a hand-written fixture would not
 * have thought of.
 */
const FIXTURE = readFileSync(path.join(import.meta.dirname, 'fixtures/jira-cap-59.xml'), 'utf8');

describe('sniffTicketFormat', () => {
  it('recognises the export despite the leading comment and missing declaration', () => {
    // The document opens with `<!-- RSS generated by JIRA ... -->` and has no
    // `<?xml ?>` at all, so a rule keyed on a declaration would miss every
    // real export.
    expect(FIXTURE.startsWith('<!--')).toBe(true);
    expect(FIXTURE).not.toContain('<?xml');
    expect(sniffTicketFormat(FIXTURE).format).toBe('jira-xml');
  });

  it('reads a .doc that is really HTML as HTML', () => {
    expect(sniffTicketFormat('<html><body><h1>CAP-59</h1></body></html>').format).toBe('html');
  });

  it('recognises a PDF by its magic number', () => {
    expect(sniffTicketFormat('%PDF-1.7\n%\xE2\xE3\xCF\xD3\n').format).toBe('pdf');
  });

  it('falls back to text for anything else', () => {
    expect(sniffTicketFormat('As a visitor I want to read a story.').format).toBe('text');
  });

  it('does not claim an issue when the feed carries none', () => {
    expect(sniffTicketFormat('<rss><channel><title>Jira</title></channel></rss>').format).toBe('html');
  });
});

describe('parseJiraXml', () => {
  const ticket = parseJiraXml(FIXTURE);

  it('reads the issue fields', () => {
    expect(ticket.key).toBe('CAP-59');
    expect(ticket.summary).toBe('Featured Story Card');
    expect(ticket.type).toBe('Story');
    expect(ticket.status).toBe('Backlog');
    expect(ticket.priority).toBe('Low');
    expect(ticket.parent).toBe('CAP-45');
    expect(ticket.labels).toEqual(['Sprint_1']);
  });

  it('keeps only custom fields that carried a value', () => {
    // Rank and Development are on every issue and say nothing about it.
    expect(ticket.fields).toEqual({ Sprint: 'CAP Sprint 1' });
  });

  it('names every attachment without reading one', () => {
    expect(ticket.attachments).toHaveLength(4);
    expect(ticket.attachments.map((entry) => entry.name)).toContain('image-20260825-095116.png');
    expect(ticket.attachments[0]?.bytes).toBeGreaterThan(0);
  });

  it('cuts the description into passages with ids short enough to copy exactly', () => {
    // Ordinals, not slugs of the source anchor. A real run lost 28 of 61
    // claims to a model transcribing
    // `scenariossitevisitor-guestuserexperience` as
    // `sitevisitor-guestuserexperience`.
    const ids = ticket.passages.map((passage) => passage.id);
    expect(ids).toEqual(['p1', 'p2', 'p3', 'p4', 'p5', 'p6']);
    expect(ids.every((id) => id.length <= 3)).toBe(true);
  });

  it('keeps the source anchor beside the id, for a reader', () => {
    const criteria = ticket.passages.find((passage) => passage.heading === 'Acceptance Criteria');
    expect(criteria?.anchor).toBe('AcceptanceCriteria');
    // Percent-encoded by Confluence; decoded here.
    expect(
      ticket.passages.find((passage) => passage.heading.startsWith('Authoring Specifications'))?.anchor,
    ).toBe('AuthoringSpecifications(HowtoEditThisBlock)');
  });

  it('keeps the acceptance criteria a list', () => {
    const criteria = ticket.passages.find((passage) => passage.heading === 'Acceptance Criteria');
    expect(criteria?.heading).toBe('Acceptance Criteria');
    // Eight criteria, each its own bullet -- flattening them to prose would
    // lose the thing a reader has to enumerate.
    expect(criteria?.body.split('\n').filter((line) => line.startsWith('- '))).toHaveLength(8);
  });

  it('keeps the authoring specification a table', () => {
    const authoring = ticket.passages.find((passage) =>
      passage.heading.startsWith('Authoring Specifications'),
    );
    expect(authoring?.body).toContain('| # | Field Name | Required? | Description |');
    // Twelve fields plus a header and the separator rule.
    expect(authoring?.body.split('\n').filter((line) => line.startsWith('|'))).toHaveLength(14);
  });

  it('recovers a row the author’s own pipe character split', () => {
    const authoring = ticket.passages.find((passage) =>
      passage.heading.startsWith('Authoring Specifications'),
    );
    const row = authoring?.body
      .split('\n')
      .find((line) => line.includes('Secondary CTA Label'));

    expect(row).toBeDefined();
    // Confluence read the literal `|` in "divider line (|)" as a cell
    // separator, so the export has five cells against a four-column header.
    // Rejoining the overflow puts the sentence back whole.
    expect(row).toContain('when 1 or no CTAs are defined');
    expect(row).toContain('divider line (\\|)');
    // Four columns, so four separators plus the two edges.
    expect(row?.match(/(?<!\\)\|/g)).toHaveLength(5);
  });

  it('reads the comments, which carry requirements the description does not', () => {
    expect(ticket.comments).toHaveLength(1);
    const body = ticket.comments[0]?.body ?? '';
    // The description's field table says the hero takes photo assets; this
    // comment says video autoplay is supported. That disagreement is the sort
    // of thing the analysis exists to surface, and dropping comments would
    // hide it.
    expect(body).toContain('video autoplay is technically supported');
    expect(ticket.description).toContain('high-resolution photo assets');
    expect(ticket.description).not.toContain('video autoplay');
  });

  it('strips the rule that separates a passage from the next heading', () => {
    for (const passage of ticket.passages) {
      expect(passage.body.endsWith('---')).toBe(false);
    }
  });

  it('refuses a feed with no issue in it', () => {
    expect(() => parseJiraXml('<rss><channel></channel></rss>')).toThrow(/no <item>/);
  });
});

describe('splitPassages', () => {
  it('names an unheaded opening passage rather than dropping it', () => {
    const passages = splitPassages('Some intent.\n\n## Detail\n\nBody.', []);
    expect(passages[0]?.heading).toBe('Introduction');
    expect(passages[0]?.body).toBe('Some intent.');
  });

  it('numbers passages in order, with no anchor needed', () => {
    const passages = splitPassages('## Acceptance Criteria\n\nBody.', []);
    expect(passages[0]?.id).toBe('p1');
    expect(passages[0]?.anchor).toBeUndefined();
  });

  it('keeps repeated headings distinct without inventing a suffix', () => {
    const passages = splitPassages('## Notes\n\nOne.\n\n## Notes\n\nTwo.', []);
    expect(passages.map((passage) => passage.id)).toEqual(['p1', 'p2']);
    expect(passages.map((passage) => passage.heading)).toEqual(['Notes', 'Notes']);
  });
});
